# This file is to test how to deploy Backstage in kubernetes
# Following the tutorial: https://backstage.io/docs/deployment/k8s/
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: backstage
type: Opaque
data:
  POSTGRES_USER: YWRtaW4= # admin en base64
  POSTGRES_PASSWORD: YWRtaW4= # admin en base64

